<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.github.exabrial</groupId>
		<artifactId>java25-parent-pom</artifactId>
		<version>1-SNAPSHOT</version>
	</parent>
	<groupId>com.github.exabrial.cdi.jms</groupId>
	<artifactId>cdi-jms-parent</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<name>${project.artifactId}</name>
	<description>CDI JMS Libraries</description>

	<licenses>
		<license>
			<name>EUPL-1.2</name>
			<url>https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/2020-03/EUPL-1.2%20EN.txt</url>
			<distribution>repo</distribution>
			<comments>European Union Public Licence v1.2</comments>
		</license>
	</licenses>

	<developers>
		<developer>
			<id>exabrial</id>
			<name>Jonathan S. Fisher</name>
			<email>exabrial@gmail.com</email>
			<url>https://github.com/exabrial</url>
			<properties>
				<dev.pgp.fingerprint>871638A21A7F2C38066471420306A354336B4F0D</dev.pgp.fingerprint>
			</properties>
		</developer>
	</developers>

	<modules>
		<module>cdi-jms-common</module>
		<module>cdi-jms-async-api</module>
		<module>cdi-jms-async</module>
		<module>cdi-jms-transport-model</module>
		<module>cdi-jms-transport-api</module>
		<module>cdi-jms-transport</module>
		<module>cdi-jms-defaults</module>
		<module>cdi-jms-ee</module>
		<module>cdi-jms-activemq-se</module>
		<module>cdi-jms-listeners-se</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.github.exabrial.cdi.jms</groupId>
				<artifactId>cdi-jms-activemq-se</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.exabrial.cdi.jms</groupId>
				<artifactId>cdi-jms-async</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.exabrial.cdi.jms</groupId>
				<artifactId>cdi-jms-async-api</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.exabrial.cdi.jms</groupId>
				<artifactId>cdi-jms-common</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.exabrial.cdi.jms</groupId>
				<artifactId>cdi-jms-defaults</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.exabrial.cdi.jms</groupId>
				<artifactId>cdi-jms-ee</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.exabrial.cdi.jms</groupId>
				<artifactId>cdi-jms-listeners-se</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.exabrial.cdi.jms</groupId>
				<artifactId>cdi-jms-transport</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.exabrial.cdi.jms</groupId>
				<artifactId>cdi-jms-transport-api</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.exabrial.cdi.jms</groupId>
				<artifactId>cdi-jms-transport-model</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.github.exabrial.cdi</groupId>
				<artifactId>cdi-common</artifactId>
				<version>1.0.0-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>com.github.exabrial.cdi.nanoscopes</groupId>
				<artifactId>nanoscopes</artifactId>
				<version>1.0.0-SNAPSHOT</version>
			</dependency>
			
			<dependency>
				<groupId>org.apache.activemq</groupId>
				<artifactId>activemq-client-jakarta</artifactId>
				<version>5.19.7</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>3.17.0</version>
			</dependency>
			<dependency>
				<groupId>org.apache.johnzon</groupId>
				<artifactId>johnzon-jsonb</artifactId>
				<version>2.0.2</version>
			</dependency>

			<dependency>
				<groupId>jakarta.annotation</groupId>
				<artifactId>jakarta.annotation-api</artifactId>
				<version>2.1.1</version>
			</dependency>
			<dependency>
				<groupId>jakarta.ejb</groupId>
				<artifactId>jakarta.ejb-api</artifactId>
				<version>4.0.1</version>
			</dependency>
			<dependency>
				<groupId>jakarta.enterprise</groupId>
				<artifactId>jakarta.enterprise.cdi-api</artifactId>
				<version>4.0.1</version>
			</dependency>
			<dependency>
				<groupId>jakarta.interceptor</groupId>
				<artifactId>jakarta.interceptor-api</artifactId>
				<version>2.1.0</version>
			</dependency>
			<dependency>
				<groupId>jakarta.jms</groupId>
				<artifactId>jakarta.jms-api</artifactId>
				<version>3.1.0</version>
			</dependency>
			<dependency>
				<groupId>jakarta.json</groupId>
				<artifactId>jakarta.json-api</artifactId>
				<version>2.1.1</version>
			</dependency>
			<dependency>
				<groupId>jakarta.json.bind</groupId>
				<artifactId>jakarta.json.bind-api</artifactId>
				<version>3.0.0</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
</project>
