<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.github.exabrial.cdi.jms</groupId>
		<artifactId>cdi-jms-parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>cdi-jms-listeners-se</artifactId>
	<packaging>jar</packaging>
	<name>${project.artifactId}</name>
	<description>JMS listener management for CDI SE: managed @MessageDriven and ephemeral listeners</description>

	<dependencies>
		<dependency>
			<groupId>com.github.exabrial.cdi.jms</groupId>
			<artifactId>cdi-jms-api</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.github.exabrial.cdi.jms</groupId>
			<artifactId>cdi-jms-transport-wiremodel</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>com.github.exabrial.cdi.jms</groupId>
			<artifactId>cdi-jms-activemq-se</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>com.github.exabrial.cdi.jms</groupId>
			<artifactId>cdi-jms-defaults</artifactId>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>jakarta.ejb</groupId>
			<artifactId>jakarta.ejb-api</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.jms</groupId>
			<artifactId>jakarta.jms-api</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>jakarta.json.bind</groupId>
			<artifactId>jakarta.json.bind-api</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.johnzon</groupId>
			<artifactId>johnzon-jsonb</artifactId>
			<scope>runtime</scope>
		</dependency>
	</dependencies>
</project>
