<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.github.exabrial.cdi.jms</groupId>
		<artifactId>cdi-jms-parent</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>cdi-jms-activemq-se</artifactId>
	<packaging>jar</packaging>
	<name>${project.artifactId}</name>
	<description>ActiveMQ SE connector: @Alternative producers for ConnectionFactory and JMSContext in a CDI SE container</description>

	<dependencies>
		<dependency>
			<groupId>com.github.exabrial.cdi</groupId>
			<artifactId>cdi-common</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.github.exabrial.cdi.jms</groupId>
			<artifactId>cdi-jms-common</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.github.exabrial.cdi.jms</groupId>
			<artifactId>cdi-jms-ee</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.github.exabrial.cdi.jms</groupId>
			<artifactId>cdi-jms-transport-model</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.github.exabrial.cdi.nanoscopes</groupId>
			<artifactId>nanoscopes</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-client-jakarta</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.enterprise</groupId>
			<artifactId>jakarta.enterprise.cdi-api</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.inject</groupId>
			<artifactId>jakarta.inject-api</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.jms</groupId>
			<artifactId>jakarta.jms-api</artifactId>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>jakarta.json</groupId>
			<artifactId>jakarta.json-api</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.json.bind</groupId>
			<artifactId>jakarta.json.bind-api</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.johnzon</groupId>
			<artifactId>johnzon-jsonb</artifactId>
			<scope>runtime</scope>
		</dependency>
	</dependencies>
</project>
